### ISSUE TITLE
Getting bad decrypt 

### ISSUE THREAD

**Issue by 2srk** [JFC-Group/AF-Customisation#1]
I got the backup from the router in "backup-jio-2024-11-08_enc.tar.gz" that have "backup-jio-2024-11-08_enc" which I renamed to backup.enc. Although I use server. key from (https://small.fileditchstuff.me/s18/TGJFgrgUrrolDsBKDatu.tar.gz) and uploading this firmware to the router, I am getting this error "bad decrypt
80CB6347937F0000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:../providers/implementations/ciphers/ciphercommon_block.c:129:" 

Any help will be Great.

**Comment by Otus9051** [comment]
The OpenSSL Version used in the firmware is OpenSSL 1.1.1s. Please use any 1.1.1x version instead of OpenSSL 3.x
More info: https://broadband.forum/threads/jio-airfiber-root-access-guide.231307/post-1673356
