### ISSUE TITLE
Wrong Number of Files to Check in New Script.

### ISSUE THREAD

**Issue by 2srk** [JFC-Group/AF-Customisation#3]
In the Script, it should be "if [ "$#" -ne 1]; then" instead of if "[ "$#" -ne 2 ]; then" on line 36 as of now we only need 1 file.  BTW thanks for Creating this!!!

**Comment by 2srk** [comment]
And FYI Decryption works on version 3.0.2. (Mine Worked at least.)

**Comment by ramrattle** [comment]
Hi @2srk @itsyourap 
 I have firmware version JIO_JIDU6J11_R1.8.7.2 and JIDU6811 model, Im getting below error, do you have any idea why this file is not present

+ echo 'Error: mwan3.user file '\''extracted_backup/etc/mwan3.user'\'' does not exist in the backup.'
Error: mwan3.user file 'extracted_backup/etc/mwan3.user' does not exist in the backup.

**Comment by itsyourap** [comment]
#5

**Comment by itsyourap** [comment]
Fixed by #7
