### ISSUE TITLE
Help reaching ODU

### ISSUE THREAD

**Issue by ramrattle** [JFC-Group/AF-Customisation#4]
Thanks a lot for putting this document, I have a ODU52041 and IDU6811, wanted to know if this work for these mode??

Also wanted to know how to reach the ODU? the manual says jioodu.local.html will open the dashboard but its not working for me, any help will be really appreciated.

**Comment by arevindh** [comment]
I have the same device.

**Comment by ramrattle** [comment]
Thanks for the reply, do you remember the login cred with you you logged in to the odu? did the dashboard open up with jioodu.local.html?

**Comment by ramrattle** [comment]
> I have the same device. Last time plugged in the ODU to lan to access it.

@arevindh I tried using lan (connecting the cable going towards idu to laptop), directly putting laptop in lan port, directly looking for ODU IP and pinging but nothing helped, if you you have successfully reached ODU, can you pls help with this?

**Comment by arevindh** [comment]
> > I have the same device. Last time plugged in the ODU to lan to access it.
> 
> @arevindh I tried using lan (connecting the cable going towards idu to laptop), directly putting laptop in lan port, directly looking for ODU IP and pinging but nothing helped, if you you have successfully reached ODU, can you pls help with this?

Which are the IPs you device got from the direct connection ?

**Comment by ramrattle** [comment]
thanks,  I did not get any valid IP (tried with both windows and macbook), I see link is active but it gets some  weird x.x.29.1 IPV4 address,  tried to look into ipconfig and it had some  ipv6 LL address and nothing in the gateway, tried rebooted the ODU multiple times but no luck. From IDU root I see few ipv6 address  but not able to get any response for wget  or curl

**Comment by arevindh** [comment]
> thanks,  I did not get any valid IP (tried with both windows and macbook), I see link is active but it gets some  weird x.x.29.1 IPV4 address,  tried to look into ipconfig and it had some  ipv6 LL address and nothing in the gateway, tried rebooted the ODU multiple times but no luck. From IDU root I see few ipv6 address  but not able to get any response for wget  or curl

They might have removed the access. 
Tried from my side also , no luck.

**Comment by ramrattle** [comment]
> > thanks,  I did not get any valid IP (tried with both windows and macbook), I see link is active but it gets some  weird x.x.29.1 IPV4 address,  tried to look into ipconfig and it had some  ipv6 LL address and nothing in the gateway, tried rebooted the ODU multiple times but no luck. From IDU root I see few ipv6 address  but not able to get any response for wget  or curl
> 
> They might have removed the access. Tried from my side also , no luck.

Thanks a lot for checking it, in future if you find some way pls  do let me know, thanks.

**Comment by ramrattle** [comment]
Hi @jckefan , thanks  a lot for your suggestion, I was able  to  get a  valid ipv6  address to my laptop in 2409:40f2:14f_XXX range however I'm not able to reach the odu page or just typing   gateway  address in browser, can you please help me with this? where you able to access the page anytime?

**Comment by jckefan** [comment]
Are you able to ping the gateway IP address? How are typing the address in the browser? It should be typed as http://[2409:40f2:14f_XXX]

**Comment by ramrattle** [comment]
@jckefan Dude, thanks a lot it  works with the IP!!!  any idea how to make it work over wifi?? I see a settings called EoGRE (which is selected by  default), bridge mode, switch  mode etc, perhaps  if i switch to bridge mode will it work?

**Comment by jckefan** [comment]
No, idea! What credentials did you use to login into the ODU? Mine came with a custom password.

**Comment by ramrattle** [comment]
custom  one? can you please brief bit more?   I tried the default admin/Jiocentrum, it didn't  work, then found [this ](https://youtu.be/R9lWkkRH38g?si=-SN8J468hnVooZX8), turns out username is Admin with a capital a :-)

**Comment by jckefan** [comment]
When I had tried logging into my ODU I had tried multiple usernames and passwords, but all attempted had failed. So I had assumed that my ODU has an unknown password. However, I was wrong, as suggested by you, I again tried logging into the ODU with a capital letter Admin, and I was able to log in.

May I ask, what are you trying to achieve by accessing your ODU?

**Comment by ramrattle** [comment]
glad to know it works, I work in telecom development domain so I need to see how the hardware and implementation works that's my intention.
