### ISSUE TITLE
Can you please tell me how you got the firmware? 

### ISSUE THREAD

**Issue by ramrattle** [JFC-Group/AF-Customisation#6]
"With the firmware in hand, and some binwalking around"

Thanks a lot for the tutorial, Im able to root login to the IDU!!! just wanted to know how did you get hold of the firmware to do this analysis?

**Comment by KuganCodes** [comment]
Hii Ramrattle

"With the firmware in hand, and some binwalking around"

Thanks a lot for the tutorial, Im able to root login to the IDU!!! just wanted to know how did you get hold of the firmware to do this analysis?

My Question  : without the firmware how did you got root access ?

**Comment by ramrattle** [comment]
@KuganCodes He had a raw bin of the firmware from  which he understood the key used is not the actual key but the word "key", root access is enabled by restoring a config file which triggered a shell to enable root with mentioned password, you don't need a firmware image to do this, its pure reverse engineering.

**Comment by KuganCodes** [comment]
@ramrattle Thanks for the answer ,the wan only accepts ipv6 addresses from the ODU (outdoor unit) from RADVD Daemon  running but not able to get root access to ODU which i have tried , can you guide with the steps pls pls !!

**Comment by ramrattle** [comment]
AFAIK ODU was not rooted by anyone yet

**Comment by KuganCodes** [comment]
@ramrattle  can you guide with steps with IDU not about the ODU !

**Comment by itsyourap** [comment]
>  just wanted to know how did you get hold of the firmware to do this analysis?

@ramrattle let's just say there was once a BroadbandForum post which hinted on how to get the firmware.
